/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of URLs
         * @description Returns a list of URLs provided by this API endpoint.
         */
        get: operations["eliLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * a list of publishers
         * @description Returns a list of publishing houses
         */
        get: operations["getPublishers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * search for acts
         * @description Finds acts that match a specified criteria.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act details
         * @description Finds an act by a publishing address
         */
        get: operations["getActDetailsPub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * publisher info
         * @description Returns an information about given publisher. The information about publisher contains a list of years in which there are any acts published.
         */
        get: operations["getYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * acts in year
         * @description Returns a list of acts for a given publisher and a given year
         */
        get: operations["getActsInYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * volumes
         * @description returns a list of volumes for a given publisher and a given year
         */
        get: operations["getVolumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * acts in volume
         * @description returns a list of acts for a given volume
         */
        get: operations["getVolume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * get act in a volume
         * @description returns an act in a given volume
         */
        get: operations["getActInVolume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act references
         * @description Returns a map of type -> list of references for a given act
         */
        get: operations["getActInVolumeReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/struct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act structure
         * @description Returns a structure of a document (chapters, articles, paragraphs, ...)
         */
        get: operations["getActInVolumeStruct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/text.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text
         * @description Display a text of a given act in the HTML format
         */
        get: operations["getActInVolumeHTML"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/text.html/{tree}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act fragment
         * @description Display a fragment of a given act in the HTML format
         */
        get: operations["getActInVolumeHTMLFragment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/text.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text in PDF
         * @description Download a text for a given act in the PDF format
         */
        get: operations["getActInVolumePDF"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/volumes/{volume}/{position}/text/{type}/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text
         * @description Download a text for a given act with specified type and name
         */
        get: operations["getActInVolumeFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act details
         * @description Finds an act by a publisher, year and a number
         */
        get: operations["getActDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act references
         * @description Returns a map of type -> list of references for a given act
         */
        get: operations["getActReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/struct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act structure
         * @description Returns a structure of a document (chapters, articles, paragraphs, ...)
         */
        get: operations["getActStruct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/text.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text
         * @description Display a text of a given act in the HTML format
         */
        get: operations["getActHTML"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/text.html/{tree}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act fragment
         * @description Display a fragment of a given act in the HTML format
         */
        get: operations["getActHTMLFragment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/text.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text in PDF
         * @description Download a text for a given act in the PDF format
         */
        get: operations["getActPDF"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acts/{publisher}/{year}/{position}/text/{type}/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * act text
         * @description Download a text for a given act with specified type and name
         */
        get: operations["getActFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/acts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * changed acts
         * @description Returns a list of changed acts, sorted by the change date.
         */
        get: operations["getChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of institutions
         * @description Returns a list of institutions.
         */
        get: operations["getInstitutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of keywords
         * @description Returns a list of keywords.
         */
        get: operations["getKeywords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of reference types
         * @description Returns a list of reference types.
         */
        get: operations["getReferenceTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of statuses
         * @description Returns a list of statuses that an act can have.
         */
        get: operations["getStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * title search
         * @description Returns a list of words that appear in titles of acts
         */
        get: operations["searchByTitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * list of types
         * @description Returns a list of document types.
         */
        get: operations["getTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Information about an act. */
        Act: {
            /**
             * @description an address of publication. An address is in format {publisher}{year}{volume}{position}.
             * @example WDU20170002196
             */
            address?: string;
            /**
             * @description a code of a publisher
             * @example DU
             */
            publisher?: string;
            /**
             * Format: int32
             * @description a year of publication
             * @example 2017
             */
            year?: number;
            /**
             * Format: int32
             * @description a volume of a publication. Specifies a volume in year. After year 2012 there are no volumes and this field should have value '0'.
             * @example 1
             */
            volume?: number;
            /**
             * Format: int32
             * @description a position in a year (or in a volume before year 2012)
             * @example 2196
             */
            pos?: number;
            /**
             * @description a title of this act
             * @example Obwieszczenie Marszałka Sejmu Rzeczypospolitej Polskiej z dnia 9 listopada 2017 r. w sprawie ogłoszenia jednolitego tekstu ustawy o kształtowaniu ustroju rolnego
             */
            title?: string;
            /**
             * @description a display address
             * @example Dz.U. 2017 poz. 2332
             */
            displayAddress?: string;
            /**
             * Format: date
             * @description promulgation date
             * @example 2022-03-10
             */
            promulgation?: string;
            /**
             * Format: date
             * @description announcement date
             * @example 2022-03-10
             */
            announcementDate?: string;
            /** @description a flag indicating this act has a PDF text */
            textPDF?: boolean;
            /** @description a flag indicating this act has a HTML text */
            textHTML?: boolean;
            /**
             * Format: date-time
             * @description date and time of last change in a document
             * @example 2018-01-05 12:50
             */
            changeDate?: string;
            /**
             * @description an European Legislation Identifier
             * @example DU/2017/2196
             */
            ELI?: string;
            /**
             * @description a type of the act
             * @example Ustawa
             */
            type?: string;
            /**
             * @description status of the act
             * @example obowiązujący
             */
            status?: string;
            /**
             * Format: date
             * @description date of entry into force
             * @example 2022-03-10
             */
            entryIntoForce?: string;
            /**
             * Format: date
             * @description date of binding force
             * @example 2022-03-10
             */
            validFrom?: string;
            /**
             * Format: date
             * @description date of repeal of the act
             * @example 2022-03-10
             */
            repealDate?: string;
            /**
             * Format: date
             * @description date of expiration of the act
             * @example 2022-03-10
             */
            expirationDate?: string;
            /**
             * Format: date
             * @description date of legal status
             * @example 2022-03-10
             */
            legalStatusDate?: string;
            /** @description is the act in force */
            inForce?: string & components["schemas"]["StatusInForce"];
            /** @description comments */
            comments?: string;
            /**
             * @description issuing authority
             * @example MIN. ROLNICTWA I ROZWOJU WSI
             */
            releasedBy?: string[];
            /** @description authorized body */
            authorizedBody?: string[];
            /**
             * @description obligated authority
             * @example MIN. WŁAŚCIWY DS ROZWOJU WSI
             */
            obligated?: string[];
            /** @description a list of european directives */
            directives?: components["schemas"]["Directive"][];
            /**
             * @description a list of keywords associated with this act
             * @example produkty rolnicze
             */
            keywords?: string[];
            /**
             * @description a list of names associated with this act
             * @example Rzecznik Praw Pacjenta
             */
            keywordsNames?: string[];
            /** @description a list of texts */
            texts?: components["schemas"]["ActText"][];
            /** @description a list of previous titles of this act */
            previousTitle?: string[];
            /** @description a list of prints */
            prints?: components["schemas"]["PrintRef"][];
            /** @description a list of references */
            references?: {
                [key: string]: components["schemas"]["ReferenceInfo"][];
            };
        } | null;
        /** @description Basic information about an act. */
        ActInfo: {
            /**
             * @description an address of publication. An address is in format {publisher}{year}{volume}{position}.
             * @example WDU20170002196
             */
            address?: string;
            /**
             * @description a code of a publisher
             * @example DU
             */
            publisher?: string;
            /**
             * Format: int32
             * @description a year of publication
             * @example 2017
             */
            year?: number;
            /**
             * Format: int32
             * @description a volume of a publication. Specifies a volume in year. After year 2012 there are no volumes and this field should have value '0'.
             * @example 1
             */
            volume?: number;
            /**
             * Format: int32
             * @description a position in a year (or in a volume before year 2012)
             * @example 2196
             */
            pos?: number;
            /**
             * @description a title of this act
             * @example Obwieszczenie Marszałka Sejmu Rzeczypospolitej Polskiej z dnia 9 listopada 2017 r. w sprawie ogłoszenia jednolitego tekstu ustawy o kształtowaniu ustroju rolnego
             */
            title?: string;
            /**
             * @description a display address
             * @example Dz.U. 2017 poz. 2332
             */
            displayAddress?: string;
            /**
             * Format: date
             * @description promulgation date
             * @example 2022-03-10
             */
            promulgation?: string;
            /**
             * Format: date
             * @description announcement date
             * @example 2022-03-10
             */
            announcementDate?: string;
            /** @description a flag indicating this act has a PDF text */
            textPDF?: boolean;
            /** @description a flag indicating this act has a HTML text */
            textHTML?: boolean;
            /**
             * Format: date-time
             * @description date and time of last change in a document
             * @example 2018-01-05 12:50
             */
            changeDate?: string;
            /**
             * @description an European Legislation Identifier
             * @example DU/2017/2196
             */
            ELI?: string;
            /**
             * @description a type of the act
             * @example Ustawa
             */
            type?: string;
            /**
             * @description status of the act
             * @example obowiązujący
             */
            status?: string;
        };
        /** @description a sorting order */
        ActOrder: {
            /** @description a name of column to sort by */
            column?: string & components["schemas"]["SortColumn"];
            /** @description an order in which sort the data (ascending or descending) */
            dir?: string & components["schemas"]["SortDir"];
        };
        /** @description a query for searching acts */
        ActQuery: {
            /** @description include acts from Polish authorities in exile */
            exile?: boolean;
            /** @description include only acts in force */
            statusInForce?: boolean;
            /** @description a code of the selected publisher */
            publisher?: string;
            /** @description a name of the selected publisher */
            publisherName?: string;
            /**
             * Format: int32
             * @description a selected year of publication
             */
            year?: number;
            /**
             * Format: int32
             * @description a selected volume of publication
             */
            volume?: number;
            /**
             * Format: int32
             * @description a selected position of publication
             */
            position?: number;
            /** @description a title to search for */
            title?: string;
            /** @description a list of act types to search for */
            type?: string[];
            /** @description a list of keywords to search for */
            keyword?: string[];
            /** @description a type of search on date of announcement */
            dateType?: string & components["schemas"]["SearchDate"];
            /**
             * Format: date
             * @description a date of announcement to search from
             * @example 2022-03-10
             */
            dateFrom?: string;
            /**
             * Format: date
             * @description a date of announcement to search to
             * @example 2022-03-10
             */
            dateTo?: string;
            /** @description a type of search on date of effect */
            dateEffectType?: string & components["schemas"]["SearchDate"];
            /**
             * Format: date
             * @description a date of effect to search from
             * @example 2022-03-10
             */
            dateEffectFrom?: string;
            /**
             * Format: date
             * @description a date of effect to search to
             * @example 2022-03-10
             */
            dateEffectTo?: string;
            /** @description a type of search on date of publication */
            pubDateType?: string & components["schemas"]["SearchDate"];
            /**
             * Format: date
             * @description a date of publication to search from
             * @example 2022-03-10
             */
            pubDateFrom?: string;
            /**
             * Format: date
             * @description a date of publication to search to
             * @example 2022-03-10
             */
            pubDateTo?: string;
            /** @description a sorting direction */
            comparator?: components["schemas"]["ActOrder"];
        };
        /** @description A reference from one act to another act. */
        ActReference: {
            /**
             * @description referenced article (optional)
             * @example art. 30a ust. 5
             */
            article?: string;
            /**
             * Format: date
             * @description a date (optional, e.g. for repeal)
             * @example 2017-01-05
             */
            date?: string;
            /**
             * Format: date-time
             * @description date and time of last change in a document
             * @example 2018-01-05 12:50
             */
            changeDate?: string;
            /** @description a referenced act */
            act?: string;
            /**
             * @description a type of reference
             * @example Akty zmieniające
             */
            type?: string;
        };
        /** @description An information about a text of an act. */
        ActText: {
            /**
             * @description a file name
             * @example D20172196.pdf
             */
            fileName?: string;
            /**
             * @description a type of a text
             * @example O
             * @enum {string}
             */
            type?: "T" | "O" | "U" | "H" | "I";
        };
        /** @description An European directive. */
        Directive: {
            /**
             * @description an identifier of the directive
             * @example 32013R0952
             */
            address?: string;
            /**
             * @description a title of the directive
             * @example Rozporządzenie Parlamentu Europejskiego i Rady (UE) nr 952/2013 z dnia 9 października 2013 r. ustanawiające unijny kodeks celny
             */
            title?: string;
            /**
             * Format: date
             * @description a date of the directive
             * @example 2013-10-09
             */
            date?: string;
        };
        /** @description An information about a print and legislative process. */
        PrintRef: {
            /**
             * Format: int32
             * @description a term of Sejm when this print was published
             * @example 8
             */
            term?: number;
            /**
             * @description a number of the print
             * @example 1407
             */
            number?: string;
            /**
             * @description a link to details of a legislative process
             * @example https://www.sejm.gov.pl/Sejm8.nsf/PrzebiegProc.xsp?nr=1407
             */
            link?: string;
            /**
             * @description a link to API for print details
             * @example https://api.sejm.gov.pl/sejm/term8/prints/1407
             */
            linkPrintAPI?: string;
            /**
             * @description a link to API for process details
             * @example https://api.sejm.gov.pl/sejm/term8/processes/1407
             */
            linkProcessAPI?: string;
        };
        /** @description An information about a publisher. */
        PublishingHouse: {
            /**
             * @description a unique code of a publisher
             * @example DU
             */
            code?: string;
            /**
             * @description a short name used to designate an act
             * @example Dz. U.
             */
            shortName?: string;
            /**
             * @description a full name of the publisher
             * @example Dziennik Ustaw
             */
            name?: string;
            /**
             * Format: int32
             * @description count of acts
             * @example 123
             */
            actsCount?: number;
            /**
             * @description a list of years for which there are acts
             * @example [
             *       1990,
             *       1991,
             *       1992
             *     ]
             */
            years?: number[];
        };
        /** @description information about a reference (with act header) */
        ReferenceDetailsInfo: {
            /** @description a referenced act */
            act?: components["schemas"]["ActInfo"];
            /**
             * @description referenced article (optional)
             * @example art. 30a ust. 5
             */
            art?: string;
            /**
             * Format: date
             * @description a date (optional, e.g. for repeal)
             * @example 2017-01-05
             */
            date?: string;
        };
        /** @description information about a reference (without act header, only act ID) */
        ReferenceInfo: {
            /**
             * @description an ELI address of the referenced act
             * @example DU/2019/1
             */
            id?: string;
            /**
             * @description referenced article (optional)
             * @example art. 30a ust. 5
             */
            art?: string;
            /**
             * Format: date
             * @description a date (optional, e.g. for repeal)
             * @example 2017-01-05
             */
            date?: string;
        };
        /** @description a map of type -> list of references, example keys: 'Akty uchylające', 'Akty zmieniające', values are type of ReferenceDetailsInfo */
        ReferencesDetailsInfo: {
            [key: string]: components["schemas"]["ReferenceDetailsInfo"][];
        };
        /** @description a map of type -> list of references, example keys: 'Akty uchylające', 'Akty zmieniające', values are type of ReferenceInfo */
        ReferencesInfo: {
            [key: string]: components["schemas"]["ReferenceInfo"][];
        };
        /** @enum {string} */
        SearchDate: "NONE" | "ON_DAY" | "BEFORE" | "AFTER" | "BETWEEN";
        /** @enum {string} */
        SortColumn: "publisher" | "position" | "title" | "change";
        /** @enum {string} */
        SortDir: "asc" | "desc";
        /** @enum {string} */
        StatusInForce: "IN_FORCE" | "NOT_IN_FORCE" | "UNKNOWN";
        /** @description A list of acts. */
        acts: {
            /** @description a list of items */
            items?: components["schemas"]["ActInfo"][];
            /**
             * Format: int32
             * @description a starting offset
             * @example 0
             */
            offset?: number;
            /**
             * Format: int32
             * @description a number of returned items
             * @example 20
             */
            count?: number;
            /**
             * Format: int32
             * @description total number of items
             * @example 23
             */
            totalCount?: number;
            /** @description a search query used to get a list of acts */
            searchQuery?: components["schemas"]["ActQuery"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    eliLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getPublishers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description publishing houses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingHouse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description a date of announcement of an act, in the format yyyy-MM-dd */
                date?: string;
                /** @description a date of effect, in the format yyyy-MM-dd */
                dateEffect?: string;
                /** @description a date of effect to search from, in the format yyyy-MM-dd */
                dateEffectFrom?: string;
                /** @description a date of effect to search to, in the format yyyy-MM-dd */
                dateEffectTo?: string;
                /** @description a date of announcement to search from, in the format yyyy-MM-dd */
                dateFrom?: string;
                /** @description a date of announcement to search to, in the format yyyy-MM-dd */
                dateTo?: string;
                /** @description specify 'E' to search in the Exile database */
                exile?: string;
                /** @description empty to search for all documents, '1' to search only for active documents */
                inForce?: string;
                /** @description a list of keywords, separated by comma */
                keyword?: string;
                /**
                 * @description a limit
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description a start index
                 * @example 100
                 */
                offset?: number;
                /** @description a position of publication */
                position?: number;
                /** @description a date of promulgation to search on, in the format yyyy-MM-dd */
                pubDate?: string;
                /** @description a date of promulgation to search from, in the format yyyy-MM-dd */
                pubDateFrom?: string;
                /** @description a date of promulgation to search to, in the format yyyy-MM-dd */
                pubDateTo?: string;
                /** @description a code of a publisher */
                publisher?: string;
                /**
                 * @description a name of a column to sort by: publisher, position, title, change
                 * @example 100
                 */
                sortBy?: string;
                /**
                 * @description a sorting direction
                 * @example asc or desc
                 */
                sortDir?: string;
                /** @description words to find in title */
                title?: string;
                /** @description a type of document */
                type?: string;
                /** @description a publication volume */
                volume?: number;
                /** @description a year of publication */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of acts matching a search criteria */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["acts"];
                };
            };
        };
    };
    getActDetailsPub: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a publishing address
                 * @example WDU19900190117
                 */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details of an act. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Act"];
                };
            };
            /** @description Act not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getYears: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a symbol (code) of a publisher
                 * @example DU
                 */
                publisher: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingHouse"];
                };
            };
        };
    };
    getActsInYear: {
        parameters: {
            query?: {
                /**
                 * @description a name of a column to sort by: publisher, position, title, change
                 * @example change
                 */
                sortBy?: string;
                /**
                 * @description a sorting direction
                 * @example desc
                 */
                sortDir?: string;
            };
            header?: never;
            path: {
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of acts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["acts"];
                };
            };
            /** @description publisher not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVolumes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    getVolume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of acts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["acts"];
                };
            };
            /** @description publisher not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActInVolume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 117
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Act"];
                };
            };
            /** @description act not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActInVolumeReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 8
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferencesDetailsInfo"];
                };
            };
            /** @description act not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActInVolumeStruct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActInVolumeHTML: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    getActInVolumeHTMLFragment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a path in the structure of a document constructed from the following parts: - ksiega or book
                 *     - tytul or titl
                 *     - dzial or bran
                 *     - rozdzial or chpt
                 *     - oddzial or schp
                 *     - artykul or art or arti
                 *     - ustep or pass
                 *     - paragraf or para
                 *     - punkt or pint
                 *     - litera or lit or lett
                 * @example rozdzial=1/art=4/para=1/ustep=3/punkt=2/litera=d
                 */
                tree: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a fragment of a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    getActInVolumePDF: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    getActInVolumeFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a name of a file to download
                 * @example D19900003.pdf
                 */
                fileName: string;
                /**
                 * @description a position of an act
                 * @example 8
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a type of text
                 * @example O
                 */
                type: string;
                /**
                 * @description a volume
                 * @example 19
                 */
                volume: number;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    getActDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 8
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details of an act. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Act"];
                };
            };
            /** @description Act not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 8
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferencesDetailsInfo"];
                };
            };
            /** @description act not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActStruct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getActHTML: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    getActHTMLFragment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a path in the structure of a document constructed from the following parts: - ksiega or book
                 *     - tytul or titl
                 *     - dzial or bran
                 *     - rozdzial or chpt
                 *     - oddzial or schp
                 *     - artykul or art or arti
                 *     - ustep or pass
                 *     - paragraf or para
                 *     - punkt or pint
                 *     - litera or lit or lett
                 * @example rozdzial=1/art=4/para=1/ustep=3/punkt=2/litera=d
                 */
                tree: string;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a fragment of a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    getActPDF: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a position of an act
                 * @example 2
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a year
                 * @example 2017
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    getActFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description a name of a file to download
                 * @example D19900003.pdf
                 */
                fileName: string;
                /**
                 * @description a position of an act
                 * @example 8
                 */
                position: number;
                /**
                 * @description a symbol of a publisher
                 * @example DU
                 */
                publisher: string;
                /**
                 * @description a type of text
                 * @example O
                 */
                type: string;
                /**
                 * @description a year
                 * @example 1990
                 */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a text of an act */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
        };
    };
    getChanges: {
        parameters: {
            query: {
                /**
                 * @description a number of entries to return, maximum is 500 entries.
                 * @example 50
                 */
                limit?: number;
                /**
                 * @description a start index
                 * @example 100
                 */
                offset?: number;
                /**
                 * @description a date to search for changes from
                 * @example 2018-01-02T12:15:34
                 */
                since: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a list of changed acts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["acts"];
                };
            };
        };
    };
    getInstitutions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getKeywords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getReferenceTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    searchByTitle: {
        parameters: {
            query?: {
                /** @description a fragment of title to search */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
