/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/csv-operations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "file": {}
                     *     }
                     */
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description The contents of the CSV file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        }[];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/csv-operations/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Mapping of column keys to display names
                         * @example {
                         *       "firstName": "First Name",
                         *       "lastName": "Last Name"
                         *     }
                         */
                        headers: {
                            [key: string]: string;
                        };
                        /**
                         * @description Array of data rows matching the header keys
                         * @example [
                         *       {
                         *         "firstName": "John",
                         *         "lastName": "Doe"
                         *       },
                         *       {
                         *         "firstName": "Jane",
                         *         "lastName": "Smith"
                         *       }
                         *     ]
                         */
                        data: {
                            [key: string]: string | number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Successfully generated CSV file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eli-operations/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The request body */
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "eli": "DU/2017/2196"
                     *     }
                     */
                    "application/json": {
                        /**
                         * ELI
                         * @description The ELI of the data
                         * @example DU/2017/2196
                         */
                        eli: string;
                    };
                };
            };
            responses: {
                /** @description The Eli resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resources - EliResource"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 404,
                         *       "message": "Resource not found."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - NotFoundErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read comprehensive metrics metrics
         * @description Returns all available metrics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comprehensive metrics metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "startTs": 1703123456789,
                         *       "uptimeMs": 3600000,
                         *       "global": {
                         *         "cacheSuccessCount": 150,
                         *         "cacheFailureCount": 50,
                         *         "cacheRequestTotal": 200,
                         *         "cacheSuccessRatio": 0.75,
                         *         "cacheFailureRatio": 0.25,
                         *         "successCount": 950,
                         *         "failureCount": 50,
                         *         "requestCount": 1000,
                         *         "timesMs": [
                         *           200,
                         *           300,
                         *           150,
                         *           400
                         *         ],
                         *         "avgTimeMs": 250.5
                         *       },
                         *       "endpoints": {
                         *         "GET:/api/v1/summarize": {
                         *           "cacheSuccessCount": 50,
                         *           "cacheFailureCount": 20,
                         *           "cacheRequestTotal": 70,
                         *           "cacheSuccessRatio": 0.714,
                         *           "cacheFailureRatio": 0.286,
                         *           "successCount": 480,
                         *           "failureCount": 20,
                         *           "requestCount": 500,
                         *           "timesMs": [
                         *             250,
                         *             350,
                         *             200
                         *           ],
                         *           "avgTimeMs": 300.2,
                         *           "lastUsedTs": 1703123456789
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Metrics - Results - Metrics"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/global": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read global metrics metrics
         * @description Returns server-wide statistics and performance metrics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-wide statistics and performance metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "cacheSuccessCount": 150,
                         *       "cacheFailureCount": 50,
                         *       "cacheRequestTotal": 200,
                         *       "cacheSuccessRatio": 0.75,
                         *       "cacheFailureRatio": 0.25,
                         *       "successCount": 950,
                         *       "failureCount": 50,
                         *       "requestCount": 1000,
                         *       "timesMs": [
                         *         200,
                         *         300,
                         *         150,
                         *         400
                         *       ],
                         *       "avgTimeMs": 250.5
                         *     }
                         */
                        "application/json": components["schemas"]["Metrics - Results - GlobalMetrics"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/endpoint/{endpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read metrics for a specific endpoint
         * @description Returns performance metrics for a specific endpoint
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Endpoint in format method:path (e.g., GET:/api/v1/summarize) */
                    endpoint: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Performance metrics for a specific endpoint */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Metrics - Results - EndpointMetrics"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 404,
                         *       "message": "Resource not found."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - NotFoundErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get metrics for all endpoints
         * @description Returns performance metrics for all tracked endpoints
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All endpoint metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["Metrics - Results - EndpointMetrics"];
                        };
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check health
         * @description Check the health of the server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "healthy",
                         *       "uptimeMs": 3600000,
                         *       "startTimeTs": 1703123456789
                         *     }
                         */
                        "application/json": components["schemas"]["Metrics - Results - Health"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdf-operations/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "url": "https://pdfobject.com/pdf/sample.pdf"
                     *     }
                     */
                    "application/json": {
                        /**
                         * Format: uri
                         * @description The url containing an pdf file.
                         */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description The TextSummary resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resources - TextSummaryResource"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdf-operations/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "url": "https://pdfobject.com/pdf/sample.pdf"
                     *     }
                     */
                    "application/json": {
                        /**
                         * Format: uri
                         * @description The url containing an pdf file.
                         */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description The TextExtraction resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resources - TextExtractionResource"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdf-operations/summaries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource identifier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The TextExtraction resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resources - TextExtractionResource"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 404,
                         *       "message": "Resource not found."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - NotFoundErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pdf-operations/extractions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Resource identifier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The TextSummary resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resources - TextSummaryResource"];
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Resource not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 404,
                         *       "message": "Resource not found."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - NotFoundErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/translations/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        samples?: {
                            /**
                             * @description The original text
                             * @example There once was a ship.
                             */
                            original: string;
                            /**
                             * @description The translation
                             * @example Kiedyś tam był statek.
                             */
                            translation: string;
                        }[];
                        /**
                         * @description The context of the translation
                         * @example casual conversation
                         */
                        context?: string;
                        /**
                         * @description The source language
                         * @example en
                         */
                        sourceLanguage: string;
                        /**
                         * @description The target language
                         * @example pl
                         */
                        targetLanguage: string;
                        /**
                         * @description The original text
                         * @example Hello, how are you?
                         */
                        original: string;
                        /**
                         * @description The number of alternatives to generate
                         * @default 1
                         * @example 1
                         */
                        alternativesCount?: number;
                    };
                };
            };
            responses: {
                /** @description Generated translations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            translations: {
                                /**
                                 * @description The translation
                                 * @example Cześć, jak się masz?
                                 */
                                translation: string;
                            }[];
                        };
                    };
                };
                /** @description Partially generated translations (some alternatives failed to generate) */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            translations: {
                                /**
                                 * @description The translation
                                 * @example Cześć, jak się masz?
                                 */
                                translation: string;
                            }[];
                        };
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/translations/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        samples?: {
                            /**
                             * @description The original text
                             * @example There once was a ship.
                             */
                            original: string;
                            /**
                             * @description The translation
                             * @example Kiedyś tam był statek.
                             */
                            translation: string;
                        }[];
                        /**
                         * @description The context of the translation
                         * @example casual conversation
                         */
                        context?: string;
                        /**
                         * @description The source language
                         * @example en
                         */
                        sourceLanguage: string;
                        /**
                         * @description The target language
                         * @example pl
                         */
                        targetLanguage: string;
                        /**
                         * @description The original text
                         * @example Hello, how are you?
                         */
                        original: string;
                        /**
                         * @description The number of alternatives to generate
                         * @default 1
                         * @example 1
                         */
                        alternativesCount?: number;
                        /**
                         * @description The translation
                         * @example Cześć, jak się masz?
                         */
                        translation: string;
                    };
                };
            };
            responses: {
                /** @description Regenerated translations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            translations: {
                                /**
                                 * @description The translation
                                 * @example Cześć, jak się masz?
                                 */
                                translation: string;
                            }[];
                        };
                    };
                };
                /** @description Partially regenerated translations (some alternatives failed to regenerate) */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            translations: {
                                /**
                                 * @description The translation
                                 * @example Cześć, jak się masz?
                                 */
                                translation: string;
                            }[];
                        };
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/translations/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        samples?: {
                            /**
                             * @description The original text
                             * @example There once was a ship.
                             */
                            original: string;
                            /**
                             * @description The translation
                             * @example Kiedyś tam był statek.
                             */
                            translation: string;
                        }[];
                        /**
                         * @description The context of the translation
                         * @example casual conversation
                         */
                        context?: string;
                        /**
                         * @description The source language
                         * @example en
                         */
                        sourceLanguage: string;
                        /**
                         * @description The target language
                         * @example pl
                         */
                        targetLanguage: string;
                        /**
                         * @description The original text
                         * @example Hello, how are you?
                         */
                        original: string;
                        /**
                         * @description The translation
                         * @example Cześć, jak się masz?
                         */
                        translation: string;
                    };
                };
            };
            responses: {
                /** @description Translation verification result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Whether the translation is valid
                             * @example true
                             */
                            isValid: boolean;
                            issues: string[];
                            /**
                             * @description The score of the translation
                             * @example 80
                             */
                            score: number;
                            suggestions: string[];
                        };
                    };
                };
                /** @description Bad request error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - BadRequestErrorResponse"];
                    };
                };
                /** @description Timeout error */
                408: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - TimeoutErrorResponse"];
                    };
                };
                /** @description Failed to process the entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": 422,
                         *       "message": "Failed to process the entity."
                         *     }
                         */
                        "application/json": components["schemas"]["Core - Errors - UnprocessableEntityErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Core - Errors - InternalServerErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "status": 400,
         *       "message": "bad request"
         *     }
         */
        "Core - Errors - BadRequestErrorResponse": {
            /** @description The error message of the response. */
            message: string;
            /**
             * @description The status code of the response.
             * @enum {number}
             */
            status: 400;
        };
        /**
         * @example {
         *       "status": 500,
         *       "message": "Internal server error"
         *     }
         */
        "Core - Errors - InternalServerErrorResponse": {
            /** @description The error message of the response. */
            message: string;
            /**
             * @description The status code of the response.
             * @enum {number}
             */
            status: 500;
        };
        "Core - Errors - NotFoundErrorResponse": {
            /** @description The error code. */
            status: number;
            /** @description The error message. */
            message: string;
        };
        /**
         * @example {
         *       "status": 408,
         *       "message": "Request took too much time"
         *     }
         */
        "Core - Errors - TimeoutErrorResponse": {
            /** @description The error message of the response. */
            message: string;
            /**
             * @description The status code of the response.
             * @enum {number}
             */
            status: 408;
        };
        "Core - Errors - UnprocessableEntityErrorResponse": {
            /** @description The error code. */
            status: number;
            /** @description The error message. */
            message: string;
        };
        /** @description Endpoint-specific metrics */
        "Metrics - Results - EndpointMetrics": {
            /** @description Number of cache hits */
            cacheSuccessCount: number;
            /** @description Number of cache misses */
            cacheFailureCount: number;
            /** @description Number of cache requests */
            cacheRequestTotal: number;
            /** @description Cache hit ratio (0-1) */
            cacheSuccessRatio: number;
            /** @description Cache miss ratio (0-1) */
            cacheFailureRatio: number;
            /** @description Number of successful requests */
            successCount: number;
            /** @description Number of failed requests */
            failureCount: number;
            /** @description Number of requests */
            requestCount: number;
            /** @description Recent response times in milliseconds */
            timesMs: number[];
            /** @description Average response time in milliseconds */
            avgTimeMs: number;
            /** @description Last access timestamp */
            lastUsedTs: number;
        };
        /** @description Global metrics */
        "Metrics - Results - GlobalMetrics": {
            /** @description Number of cache hits */
            cacheSuccessCount: number;
            /** @description Number of cache misses */
            cacheFailureCount: number;
            /** @description Number of cache requests */
            cacheRequestTotal: number;
            /** @description Cache hit ratio (0-1) */
            cacheSuccessRatio: number;
            /** @description Cache miss ratio (0-1) */
            cacheFailureRatio: number;
            /** @description Number of successful requests */
            successCount: number;
            /** @description Number of failed requests */
            failureCount: number;
            /** @description Number of requests */
            requestCount: number;
            /** @description Recent response times in milliseconds */
            timesMs: number[];
            /** @description Average response time in milliseconds */
            avgTimeMs: number;
        };
        "Metrics - Results - Health": {
            /** @description Health status */
            status: string;
            /** @description Server uptime in milliseconds */
            uptimeMs: number;
            /** @description Server start timestamp */
            startTs: number;
        };
        /** @description Comprehensive metrics metrics */
        "Metrics - Results - Metrics": {
            /** @description Start timestamp */
            startTs: number;
            /** @description Uptime in milliseconds */
            uptimeMs: number;
            global: components["schemas"]["Metrics - Results - GlobalMetrics"];
            /** @description Metrics per endpoint */
            endpoints: {
                [key: string]: components["schemas"]["Metrics - Results - EndpointMetrics"];
            };
        };
        /** @description The ELI data */
        "Resources - EliResource": {
            /**
             * @description The ELI of the data
             * @example DU/2017/2196
             */
            eli: string;
            /**
             * @description The identifier of the summary
             * @example c0a95e2d-e6a7-4edd-8cd5-e252ac0f02cf
             */
            summaryId: string | null;
            /**
             * @description The unique identifier of the resource.
             * @example c0a95e2d-e6a7-4edd-8cd5-e252ac0f02cf
             */
            id: string;
            /**
             * Format: date-time
             * @description When the resource was created.
             * @example 2021-01-01
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the resource was last updated.
             * @example 2021-01-01
             */
            updatedAt: string;
        };
        /** @description The content of a file extracted from a source */
        "Resources - TextExtractionResource": {
            /**
             * @description The type of the source.
             * @example url
             * @enum {string}
             */
            sourceType: "url";
            /**
             * @description The reference to the source of the content.
             * @example https://pdfobject.com/pdf/sample.pdf
             */
            sourceRef: string;
            /**
             * @description The text content extracted from the source
             * @example This is the full text...
             */
            content: string;
            /**
             * @description The unique identifier of the resource.
             * @example c0a95e2d-e6a7-4edd-8cd5-e252ac0f02cf
             */
            id: string;
            /**
             * Format: date-time
             * @description When the resource was created.
             * @example 2021-01-01
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the resource was last updated.
             * @example 2021-01-01
             */
            updatedAt: string;
        };
        /** @description The summaries of the text */
        "Resources - TextSummaryResource": {
            /**
             * @description The identifier of the text extraction
             * @example c0a95e2d-e6a7-4edd-8cd5-e252ac0f02cf
             */
            textExtractionId: string;
            /**
             * @description 20-40 words. One or two sentences that capture the main point.
             * @example This policy establishes new regulations for data protection in the EU.
             */
            summary: string;
            /**
             * @description 60-100 words. A paragraph that explains the key information in more detail.
             * @example The policy introduces comprehensive data protection measures affecting all EU member states. It establishes new requirements for data processing, storage, and user consent mechanisms.
             */
            details: string;
            /**
             * @description Each takeaway is one short sentence about a key fact or idea.
             * @example [
             *       "All companies must implement new consent mechanisms",
             *       "Data retention limited to 2 years",
             *       "Penalties up to 4% of revenue"
             *     ]
             */
            takeaways: string | number | boolean | null | {
                [key: string]: unknown;
            } | unknown[];
            /**
             * @description The unique identifier of the resource.
             * @example c0a95e2d-e6a7-4edd-8cd5-e252ac0f02cf
             */
            id: string;
            /**
             * Format: date-time
             * @description When the resource was created.
             * @example 2021-01-01
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the resource was last updated.
             * @example 2021-01-01
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
