/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as EliIndexRouteImport } from './../../routes/eli/index'
import { Route as DxColorPaletteRouteImport } from './../../routes/dx/color-palette'

const EliIndexRoute = EliIndexRouteImport.update({
  id: '/eli/',
  path: '/eli/',
  getParentRoute: () => rootRouteImport,
} as any)
const DxColorPaletteRoute = DxColorPaletteRouteImport.update({
  id: '/dx/color-palette',
  path: '/dx/color-palette',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dx/color-palette': typeof DxColorPaletteRoute
  '/eli': typeof EliIndexRoute
}
export interface FileRoutesByTo {
  '/dx/color-palette': typeof DxColorPaletteRoute
  '/eli': typeof EliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dx/color-palette': typeof DxColorPaletteRoute
  '/eli/': typeof EliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dx/color-palette' | '/eli'
  fileRoutesByTo: FileRoutesByTo
  to: '/dx/color-palette' | '/eli'
  id: '__root__' | '/dx/color-palette' | '/eli/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DxColorPaletteRoute: typeof DxColorPaletteRoute
  EliIndexRoute: typeof EliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/eli/': {
      id: '/eli/'
      path: '/eli'
      fullPath: '/eli'
      preLoaderRoute: typeof EliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dx/color-palette': {
      id: '/dx/color-palette'
      path: '/dx/color-palette'
      fullPath: '/dx/color-palette'
      preLoaderRoute: typeof DxColorPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DxColorPaletteRoute: DxColorPaletteRoute,
  EliIndexRoute: EliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
